import {
  BatchSummary,
  EggScan,
  Device,
  AnalyticsOverview,
  EconomicYield,
  CandlingSession,
  MortalityTrends,
  BreedMetricItem,
  User,
  AuditLog,
  HatcherySettings,
  ModelCheckpoint,
  TrainingLossEpoch,
  ModelOpsSummary,
} from '../types';

export const mockOverview: AnalyticsOverview = {
  total_eggs_scanned: 2050,
  total_fertile: 1812,
  total_infertile: 168,
  total_abnormal: 70,
  overall_fertility_rate: 88.39,
  active_batches_count: 3,
  avg_inference_ms: 27.4,
};

export const mockEconomicYield: EconomicYield = {
  penoy_culled_day_10: 168,
  penoy_unit_price_php: 14.00,
  salvage_revenue_php: 2352.00,
  incubator_energy_saved_kwh: 45.36,
  energy_savings_php: 544.32,
  duckling_sales_projected_php: 21280.00, // 532 * ₱40
  total_economic_benefit_php: 24176.32,
};

export const mockMortalityTrends: MortalityTrends = {
  day_10_early_mortality_rate: 8.8,
  day_18_mid_mortality_rate: 3.2,
  day_25_late_mortality_rate: 1.4,
  total_culled_eggs: 238,
};

export const mockBreedComparison: BreedMetricItem[] = [
  {
    breed: "KAYUMANGGI",
    total_eggs: 1000,
    fertile_count: 902,
    infertile_count: 74,
    abnormal_count: 24,
    fertility_rate: 90.2,
    hatched_count: 785,
    hatchability_rate: 87.03,
  },
  {
    breed: "ITIM",
    total_eggs: 450,
    fertile_count: 396,
    infertile_count: 38,
    abnormal_count: 16,
    fertility_rate: 88.0,
    hatched_count: 348,
    hatchability_rate: 87.88,
  },
  {
    breed: "KHAKI",
    total_eggs: 600,
    fertile_count: 546,
    infertile_count: 42,
    abnormal_count: 12,
    fertility_rate: 91.0,
    hatched_count: 532,
    hatchability_rate: 88.67,
  },
];

export const mockUsers: User[] = [
  {
    user_id: "usr-admin-01",
    email: "lead.operator@foundationu.com",
    full_name: "Ryle Gabotero",
    role: "ADMIN",
    is_active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    user_id: "usr-mgr-01",
    email: "hatchery.mgr@foundationu.com",
    full_name: "Dr. Alicia Santos",
    role: "MANAGER",
    is_active: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    user_id: "usr-op-01",
    email: "pedro.penduko@foundationu.com",
    full_name: "Pedro Penduko",
    role: "OPERATOR",
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    user_id: "usr-op-02",
    email: "juan.delacruz@foundationu.com",
    full_name: "Juan Dela Cruz",
    role: "OPERATOR",
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    user_id: "usr-op-03",
    email: "maria.clara@foundationu.com",
    full_name: "Maria Clara",
    role: "OPERATOR",
    is_active: false,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    log_id: 1084,
    user_id: "usr-admin-01",
    operator_name: "Ryle Gabotero",
    action: "BATCH_STAGE_ADVANCED",
    entity_type: "BATCH",
    entity_id: "BATCH-2026-08-KAY-01",
    details: { from: "SETTING", to: "DAY_10", operator: "Ryle Gabotero", verified_eggs: 500 },
    ip_address: "192.168.1.110",
    severity: "INFO",
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    log_id: 1083,
    user_id: "usr-op-01",
    operator_name: "Pedro Penduko",
    action: "DEVICE_CALIBRATION_UPDATED",
    entity_type: "DEVICE",
    entity_id: "STATION-01-RP5",
    details: { conveyor_speed: 12.5, conveyor_dist: 25.0, computed_delay_ms: 2000 },
    ip_address: "192.168.1.120",
    severity: "WARNING",
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    log_id: 1082,
    user_id: "usr-admin-01",
    operator_name: "Ryle Gabotero",
    action: "PDF_REPORT_GENERATED",
    entity_type: "REPORT",
    entity_id: "BATCH-2026-07-KHK-01",
    details: { format: "PDF", recipient: "Dean of Agriculture" },
    ip_address: "192.168.1.110",
    severity: "INFO",
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    log_id: 1081,
    user_id: "usr-op-02",
    operator_name: "Juan Dela Cruz",
    action: "USER_LOGIN_SUCCESS",
    entity_type: "AUTH",
    entity_id: "usr-op-02",
    details: { method: "JWT", client: "CustomTkinter Operator Station" },
    ip_address: "192.168.1.125",
    severity: "INFO",
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    log_id: 1080,
    user_id: "usr-admin-01",
    operator_name: "Ryle Gabotero",
    action: "BATCH_INITIALIZED",
    entity_type: "BATCH",
    entity_id: "BATCH-2026-08-KAY-02",
    details: { breed: "KAYUMANGGI", egg_count: 500, incubator: "INCUBATOR-B2" },
    ip_address: "192.168.1.110",
    severity: "INFO",
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    log_id: 1079,
    action: "SYSTEM_SYNC_WAL",
    entity_type: "SYSTEM",
    entity_id: "STATION-01-RP5",
    details: { records_synced: 500, sync_time_ms: 320, mode: "WAL" },
    ip_address: "192.168.1.120",
    severity: "INFO",
    created_at: new Date(Date.now() - 30 * 3600000).toISOString(),
  },
];

export const mockSettings: HatcherySettings = {
  facility_name: "Foundation University Hatchery Research Center",
  institution: "Foundation University (FU)",
  location: "Dr. Miciano Rd, Dumaguete City, Negros Oriental",
  min_confidence_threshold: 0.50,
  aspect_ratio_min: 0.65,
  aspect_ratio_max: 1.45,
  hsv_luminance_min: 40,
  penoy_unit_price: 14.00,
  duckling_unit_price: 40.00,
  kwh_rate_php: 12.50,
  sqlite_retention_days: 7,
  optical_debounce_ms: 600,
};

export const mockModelCheckpoints: ModelCheckpoint[] = [
  {
    model_id: "mdl-onnx-v1.2",
    version_tag: "yolov8n-fp16-v1.2.onnx",
    format: "ONNX_FP16",
    architecture: "YOLOv8 Nano (Candling Customized)",
    file_size_mb: 6.2,
    map50: 0.958,
    map50_95: 0.784,
    precision: 0.942,
    recall: 0.961,
    avg_latency_ms: 24.6,
    is_active: true,
    deployed_stations: ["STATION-01-RP5", "STATION-02-PC"],
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    model_id: "mdl-onnx-v1.1",
    version_tag: "yolov8s-fp16-v1.1.onnx",
    format: "ONNX_FP16",
    architecture: "YOLOv8 Small (High Capacity)",
    file_size_mb: 22.4,
    map50: 0.964,
    map50_95: 0.798,
    precision: 0.951,
    recall: 0.968,
    avg_latency_ms: 38.2,
    is_active: false,
    deployed_stations: [],
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    model_id: "mdl-pt-baseline",
    version_tag: "best.pt (PyTorch Baseline)",
    format: "PYTORCH_PT",
    architecture: "YOLOv8 Nano (Unquantized FP32)",
    file_size_mb: 12.4,
    map50: 0.958,
    map50_95: 0.784,
    precision: 0.942,
    recall: 0.961,
    avg_latency_ms: 68.4,
    is_active: false,
    deployed_stations: [],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const mockTrainingLoss: TrainingLossEpoch[] = [
  { epoch: 10, train_box_loss: 0.142, val_box_loss: 0.158, train_cls_loss: 0.198, val_cls_loss: 0.210, map50: 0.62 },
  { epoch: 20, train_box_loss: 0.108, val_box_loss: 0.119, train_cls_loss: 0.142, val_cls_loss: 0.151, map50: 0.74 },
  { epoch: 30, train_box_loss: 0.086, val_box_loss: 0.094, train_cls_loss: 0.104, val_cls_loss: 0.112, map50: 0.81 },
  { epoch: 40, train_box_loss: 0.071, val_box_loss: 0.078, train_cls_loss: 0.082, val_cls_loss: 0.089, map50: 0.86 },
  { epoch: 50, train_box_loss: 0.060, val_box_loss: 0.065, train_cls_loss: 0.068, val_cls_loss: 0.072, map50: 0.89 },
  { epoch: 60, train_box_loss: 0.052, val_box_loss: 0.057, train_cls_loss: 0.056, val_cls_loss: 0.061, map50: 0.91 },
  { epoch: 70, train_box_loss: 0.046, val_box_loss: 0.051, train_cls_loss: 0.048, val_cls_loss: 0.052, map50: 0.93 },
  { epoch: 80, train_box_loss: 0.041, val_box_loss: 0.045, train_cls_loss: 0.041, val_cls_loss: 0.045, map50: 0.94 },
  { epoch: 90, train_box_loss: 0.038, val_box_loss: 0.042, train_cls_loss: 0.036, val_cls_loss: 0.040, map50: 0.95 },
  { epoch: 100, train_box_loss: 0.035, val_box_loss: 0.039, train_cls_loss: 0.032, val_cls_loss: 0.036, map50: 0.958 },
];

export const mockModelOpsSummary: ModelOpsSummary = {
  active_model_version: "yolov8n-fp16-v1.2.onnx",
  total_training_images: 4850,
  dataset_distribution: {
    fertile: 2800,
    infertile: 1450,
    abnormal: 600,
  },
  overall_map50: 0.958,
  overall_precision: 0.942,
  overall_recall: 0.961,
  avg_latency_ms: 24.6,
  confusion_matrix: {
    classes: ["FERTILE", "INFERTILE (Penoy)", "ABNORMAL (Dead)"],
    matrix: [
      [96.4, 2.1, 1.5],  // Actual Fertile -> Pred Fertile (96.4%), Penoy (2.1%), Dead (1.5%)
      [3.2, 94.8, 2.0],  // Actual Penoy -> Pred Fertile (3.2%), Penoy (94.8%), Dead (2.0%)
      [4.2, 3.7, 92.1],  // Actual Dead -> Pred Fertile (4.2%), Penoy (3.7%), Dead (92.1%)
    ],
    raw_counts: [
      [2700, 59, 41],
      [46, 1375, 29],
      [25, 22, 553],
    ],
  },
};

export const mockSessions: CandlingSession[] = [
  {
    session_id: "sess-kay-day10",
    batch_id: "BATCH-2026-08-KAY-01",
    device_id: "STATION-01-RP5",
    stage: "DAY_10",
    operator_name: "Ryle Gabotero",
    started_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    ended_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    total_scanned: 500,
    fertile_count: 451,
    infertile_count: 37,
    abnormal_count: 12,
    avg_inference_ms: 26.4,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    session_id: "sess-itm-day18",
    batch_id: "BATCH-2026-08-ITM-01",
    device_id: "STATION-01-RP5",
    stage: "DAY_18",
    operator_name: "Pedro Penduko",
    started_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    ended_at: new Date(Date.now() - 23 * 3600000).toISOString(),
    total_scanned: 450,
    fertile_count: 396,
    infertile_count: 38,
    abnormal_count: 16,
    avg_inference_ms: 25.8,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    session_id: "sess-khk-day25",
    batch_id: "BATCH-2026-07-KHK-01",
    device_id: "STATION-02-PC",
    stage: "DAY_25",
    operator_name: "Juan Dela Cruz",
    started_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    ended_at: new Date(Date.now() - 47 * 3600000).toISOString(),
    total_scanned: 600,
    fertile_count: 546,
    infertile_count: 42,
    abnormal_count: 12,
    avg_inference_ms: 24.1,
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

export const mockBatches: BatchSummary[] = [
  {
    batch_id: "BATCH-2026-08-KAY-01",
    batch_code: "BATCH-2026-08-KAY-01",
    breed: "KAYUMANGGI",
    incubator_id: "INCUBATOR-A1",
    initial_egg_count: 500,
    set_date: new Date(Date.now() - 10 * 86400000).toISOString(),
    target_hatch_date: new Date(Date.now() + 18 * 86400000).toISOString(),
    current_stage: "DAY_10",
    status: "INCUBATING",
    hatched_count: 0,
    unhatched_count: 0,
    total_scanned: 500,
    fertile_count: 451,
    infertile_count: 37,
    abnormal_count: 12,
    fertility_rate: 90.2,
    hatchability_rate: 0,
    notes: "Kayumanggi flock from Bayawan breeder farm.",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    batch_id: "BATCH-2026-08-ITM-01",
    batch_code: "BATCH-2026-08-ITM-01",
    breed: "ITIM",
    incubator_id: "INCUBATOR-A2",
    initial_egg_count: 450,
    set_date: new Date(Date.now() - 18 * 86400000).toISOString(),
    target_hatch_date: new Date(Date.now() + 10 * 86400000).toISOString(),
    current_stage: "DAY_18",
    status: "INCUBATING",
    hatched_count: 0,
    unhatched_count: 0,
    total_scanned: 450,
    fertile_count: 396,
    infertile_count: 38,
    abnormal_count: 16,
    fertility_rate: 88.0,
    hatchability_rate: 0,
    notes: "Itim duck eggs, healthy batch.",
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    batch_id: "BATCH-2026-07-KHK-01",
    batch_code: "BATCH-2026-07-KHK-01",
    breed: "KHAKI",
    incubator_id: "INCUBATOR-B1",
    initial_egg_count: 600,
    set_date: new Date(Date.now() - 29 * 86400000).toISOString(),
    target_hatch_date: new Date(Date.now() - 1 * 86400000).toISOString(),
    current_stage: "COMPLETED",
    status: "COMPLETED",
    hatched_count: 532,
    unhatched_count: 68,
    total_scanned: 600,
    fertile_count: 546,
    infertile_count: 42,
    abnormal_count: 12,
    fertility_rate: 91.0,
    hatchability_rate: 88.67,
    notes: "Successful hatch trial, 88.7% hatchability achieved.",
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    batch_id: "BATCH-2026-08-KAY-02",
    batch_code: "BATCH-2026-08-KAY-02",
    breed: "KAYUMANGGI",
    incubator_id: "INCUBATOR-B2",
    initial_egg_count: 500,
    set_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    target_hatch_date: new Date(Date.now() + 26 * 86400000).toISOString(),
    current_stage: "SETTING",
    status: "INCUBATING",
    hatched_count: 0,
    unhatched_count: 0,
    total_scanned: 0,
    fertile_count: 0,
    infertile_count: 0,
    abnormal_count: 0,
    fertility_rate: 0,
    hatchability_rate: 0,
    notes: "Newly set batch awaiting Day 10 candling.",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockDevices: Device[] = [
  {
    device_id: "STATION-01-RP5",
    device_name: "Primary Raspberry Pi 5 Sorting Station",
    ip_address: "192.168.1.120",
    hardware_platform: "Raspberry Pi 5 (8GB)",
    model_version: "yolov8n-fp16-v1.2",
    status: "ONLINE",
    last_heartbeat: new Date().toISOString(),
    conveyor_speed_cm_s: 12.50,
    conveyor_dist_cm: 25.00,
    servo_pulse_ms: 250,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    device_id: "STATION-02-PC",
    device_name: "Secondary Workstation Station",
    ip_address: "192.168.1.125",
    hardware_platform: "Windows 11 x86_64",
    model_version: "yolov8n-fp16-v1.2",
    status: "OFFLINE",
    last_heartbeat: new Date(Date.now() - 2 * 3600000).toISOString(),
    conveyor_speed_cm_s: 10.00,
    conveyor_dist_cm: 20.00,
    servo_pulse_ms: 250,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const mockScans: EggScan[] = Array.from({ length: 40 }, (_, i) => {
  const isFertile = i % 10 !== 2 && i % 10 !== 7;
  const isInfertile = i % 10 === 2;
  const cls = isFertile ? "FERTILE" : (isInfertile ? "INFERTILE" : "ABNORMAL");
  const action = isFertile ? "ACCEPT" : "REJECT";
  const conf = isFertile ? 0.90 + (i % 8) * 0.01 : 0.85 + (i % 7) * 0.015;

  return {
    scan_id: `scan-uuid-${1000 + i}`,
    session_id: "session-uuid-kay-01",
    batch_id: "BATCH-2026-08-KAY-01",
    sequence_number: i + 1,
    final_class: cls,
    confidence: Number(conf.toFixed(4)),
    inference_ms: 24 + (i % 12),
    routing_action: action,
    detections: [{
      bbox: [0.5, 0.5, 0.42, 0.58],
      confidence: Number(conf.toFixed(4)),
      class: cls
    }],
    scanned_at: new Date(Date.now() - (40 - i) * 15000).toISOString(),
  };
});
